return {
    "I should be at the top of your 'To do list'.",
    "I have two questions for you, whatcha doin' and why ain't it me?",
    "Do you wanna watch a movie or can we make our own?",
    "Math is really simple. First, add the bed, then subtract the clothes, and hope we don't multiply.",
    "My attitude doesn't have to be the only reason I yell and roll my eyes in the back of my head.",
    "Do you like soccer? My favorite player is Ronaldo, but we can still get Messi.",
    "What's your name? I want to get it right when I shout it later.",
    "Oh, you're cold? Come inside, it's warm.",
    "They say that the tongue is the strongest muscle in the human body. Wanna fight?",
    "You look good with anything, but nothing works too.",
    "I'm having a sale in my room. All clothes are 100% off.",
    "I'm McDonald's and you're Nike. Cause you're doing it and I'm loving it.",
    "I'll be your Rapunzel and you can pull on my hair.",
    "My voice is not deep but my throat is.",
    "I should dress up as Cinderella and you see if it fits.",
    "I can't do pick-up lines cause I'd rather be pinned down than picked up.",
    "They say that kissing is a love language. So how about we have a conversation?",
    "Are you my favorite playlist? Cause I wanna turn you on and listen to you all the time.",
    "I don't know what's gotten into me lately but I hope it's you.",
    "I only agreed to be a waitress cause you said you'd give me a tip.",
    "I'm tall, but I'm shorter on my knees.",
    "Are you Alice? Cause you can get lost in this wonderland.",
    "Are you my homework? Cause I should definitely be doing you, but I'm not.",
    "Are you winter? Because you're gonna be coming soon.",
    "The word of the day is 'legs', so why don't we go home and spread the word?",
    "I won't bark. This cat is only for purring.",
    "What's your favorite planet? Cause mine's Uranus.",
    "Are you John Cena? Because I've never Cena girl like you before.",
    "Are you the school stairs? Because you take my breath away.",
    "Are you the border? Cause I can't get over you.",
    "Why do they talk so much about X and Y but not about U and I?",
    "Are you a dream? Because I want to see you every night.",
    "Are you from France? Because Eiffel for you.",
    "If I could recreate the alphabet, I would put U and I together.",
    "Are you my future? Because my parents told me to focus on you.",
    "Are you a keyboard? Because you're my type.",
    "Albert Einstein said nothing falls faster than gravity. He should've seen how fast I fell for you.",
    "Are you Scooby Doo? Because I've been looking for you.",
    "Are you a bank loan? Because you got my interest.",
    "Are you a math test? Because all I do is stare at you.",
    "On a scale of 1 to 10, I'm a 9, and you're the one I need.",
    "Are you North Korea? Cause I can't leave you.",
    "Are you an artist? Because you're really good at drawing me in.",
    "Is your mom's name practice? Because practice makes perfect and you are perfect.",
    "Are you my dog? Because you're an angel.",
    "You look like my exam paper because every time I see you, I forget everything.",
    "Is there an airport nearby, or is it my heart taking off?",
    "Are you a cop? Because you took my breath away.",
    "Can I have your jersey? Because I want your name and number.",
    "Are you Lingo? Because we could make a good duo?",
    "Sorry, I'm not good at remembering names, do you mind if I call you mine instead?",
    "We're not Manchester but we can still get United.",
    "All the pick-up lines are taken, but are you?",
    "Are you the TV? Because I like watching you.",
    "Do you know the difference between history and you? History is the past and you are my future.",
    "Are you my phone? Cause I'm addicted to you.",
    "You're a 3, because u need 2 realize that I'm the 1 made 4 you.",
    "Are you oxygen? Because I can't live without you.",
    "I have no pick-up lines, but can I pick you up instead?",
    "Are u a secret? Cause I don't think I can share you.",
    "Is your name Wi-Fi? Because I'm really feeling a connection.",
    "Einstein said that time is relative, so you're my past, present, and future.",
    "Are u the Sun? Because you shine in my eyes.",
    "Do you like superheroes like Superman and Batman? Cause I'd like to be your man.",
    "I know it's not May, but may I be yours?",
    "Are you a treasure hunt? Because I would search high and low just to unravel your mysteries.",
    "Are your parents bakers? They sure made a cutie pie.",
    "Are you a door? Because you're adorable.",
    "Do you know CPR? Because you just took my breath away.",
    "I'm pretty and you're cute, so I think we'd be pretty cute together.",
    "Hey (unimaginable rizz).",
    "Are you the sun? Because I go red whenever I see you.",
    "My favorite word is 'Universe' because it starts with U N I."
}