return = {
    "This will be the first and last roast of the night, as we've already used up your entire vocabulary.",
    "It seems like you were probably a slippery baby, right?",
    "Sorry, I can't think of an insult dumb enough for you to understand.",
    "Whenever you open your mouth, it's like, 'Whoa, somebody took too many drugs this morning.'",
    "I know it looks like I'm listening to you, but really I'm just visualizing duct tape over your mouth.",
    "The only way you'd get hurt from doing exercise would be if you sprained your finger changing the channel.",
    "There's somebody out there for everybody. For you, it's a psychiatrist.",
    "I'm sorry that my brutal honesty inconvenienced your ego.",
    "Every time I have a stick in my hand, you start looking more and more like a piñata.",
    "I consider you my sun. Now please get 93 million miles away from here.",
    "You must have been born on a highway because that's where most accidents happen.",
    "Why don't you go play in traffic?",
    "Right now, you are as useful as a soup sandwich.",
    "Mirrors can't talk. Lucky for you, they can't laugh, either.",
    "I've seen salads that dress better than you.",
    "Your biscuit's not quite done in the middle.",
    "You changed your mind? Does this one work any better?",
    "You don't need to fear success. There is really nothing for you to worry about.",
    "I have 90 billion nerves, and you've gotten on every single one of them.",
    "My life may be a joke, but it's not as funny as your outfit.",
    "I've been called worse things by better men.",
    "I didn't mean to push your buttons, I was just looking for mute.",
    "I forgot the world revolves around you. My apologies! How silly of me.",
    "I'd rather treat a baby's diaper rash than have lunch with you.",
    "I would smack you, but I'm against animal abuse.",
    "I gave out all my trophies a while ago, but here's a participation award.",
    "It's all about balance… you start talking, I stop listening.",
    "Your face is fine, but you really should put a bag over that personality.",
    "I would call you an idiot, but it would be an insult to stupid people.",
    "Are you at a loss for words, or did you exhaust your entire vocabulary?",
    "Accidents happen; the proof is sitting right there.",
    "You bring everyone so much joy… when you leave the room.",
    "You're not simply a drama queen. You're the whole royal family.",
    "You're like a gray sprinkle on a rainbow cupcake.",
    "No, that's fine. You're certainly entitled to your incorrect opinion.",
    "You are more disappointing than an unsalted pretzel.",
    "I can't wait to spend my whole life without you.",
    "Rolling your eyes isn't going to help you find your brain.",
    "Why do you look like an envelope with no address on it?",
    "If I wanted to hurt myself, I would simply jump from your ego to your IQ.",
    "Do yourself a favor and ignore anyone who tells you to be yourself. It's a bad idea in your case.",
    "I don't hate you, but if you were drowning, I would give you a high five.",
    "Everyone has a purpose in this life, and yours is to become an organ donor.",
    "It is better to keep your mouth shut and let people think you're stupid than open it and remove all doubt.",
    "Did you know your incubator had tinted windows? It was the only way to get your parents to take you home.",
    "Just remember, if anyone ever tells you that you're beautiful… they're lying.",
    "You can be anything you want, except good-looking.",
    "You're the reason God created amnesia.",
    "I'd take a photo of you, but I don't want a virus on my phone",
    "Where is your off button?",
    "I know you don't like me, and that implies you need better taste.",
    "I'm not an astronomer, but I'm pretty sure the Earth revolves around the sun… not you.",
    "I'd give you a nasty look, but it seems like you've already got one.",
    "Your birth certificate should be rewritten as a letter of apology",
    "You haven't changed since the last time I saw you. You really should.",
    "Your bad personality is the reason I prefer animals to humans.",
    "You hear that? It's the sound of me not caring.",
    "I might be fully vaccinated, but I'm still not going to hang out with you.",
    "You're so annoying, you could make a Happy Meal cry.",
    "Oh, sorry, did the middle of my sentence interrupt the beginning of yours?",
    "You know, you're just not pretty enough to have such an ugly personality.",
    "You just might be why the middle finger was invented in the first place.",
    "You have a face that makes onions cry.",
    "Have a nice day… somewhere else.",
    "You do realize we're just tolerating you, right?",
    "Were you born this stupid or did you take lessons?",
    "It's really fun watching you try to understand everything that's being said about you.",
    "You are even more useless than the 'ueue' in queue.",
    "The real heroes in this world are the ones who have to live with you.",
    "Somewhere out there a tree is producing oxygen for you. What a shame.",
    "Everyone is allowed to act stupid once in a while, but you're really abusing the privilege.",
    "If you're going to be two-faced, at least make one of them pretty.",
    "I was today years old when I realized I didn't like you.",
    "I'm not a nerd; I'm just smarter than you.",
    "If I had a dollar every time you shut up, I would give it back as a thank you.",
    "I didn't mean to offend you… but I'll take it as an additional perk.",
    "I don't want to rain on your parade. I want to summon a typhoon.",
    "You can't imagine how much happiness you can bring… by leaving the room.",
    "You're the reason this country has to put directions on shampoo bottles.",
    "How many licks 'till I get to the interesting part of this conversation?",
    "Are you doing OK today? You look like the guy in the zombie movie who's been bitten but is trying to keep it quiet.",
    "I'm listening. I just need a minute to process so much stupid information at once.",
    "You are like a software update. Every time I see you, I immediately think 'not now.'",
    "Don't worry… the first 40 years of childhood are always the hardest.",
    "It's impossible to underestimate you.",
    "I like the way you comb your hair. It's impressive how you're able to hide the horns.",
    "If I throw a stick, will you chase it? I really want out of this conversation.",
    "You're the reason gene pools need lifeguards.",
    "I don't know what makes you so stupid, but it's really doing the job.",
    "The truth will set you free. You're the worst. OK, you're free to go.",
    "Do you think your parents realize that they're living proof that two wrongs don't make a right?",
    "Give me a minute; I'm trying to think of an insult simple enough for you to understand!",
    "Congratulations on being the top of the bell curve.",
    "I've heard a smarter statement come out in a fart.",
    "I look at you and think… two billion years of evolution for this?",
    "I told my therapist about you. She didn't believe me.",
    "Don't be ashamed of who you are. That's a job for your parents.",
    "When I listen to you, I think you really are going to go far. I hope you stay there.",
    "When I see you coming, I get pre-annoyed. I figure it's smart to give myself a head start.",
    "Whoever told you to be yourself gave you bad advice.",
    "I think you just need a high five… in the face… with a chair.",
    "When I look at you, I think to myself where have you been my whole life? And can you go back there?",
    "Light travels faster than sound. It explains why you seemed smart… until I finally heard you speak.",
    "Your secrets are always safe with me. I don't even listen when you share them.",
    "When God made you, you must have been on the bottom of his 'to-do' list.",
    "Everyone brings happiness to a room. I bring happiness when I walk in, and you bring happiness when you leave.",
    "Sweetheart, the only thing bothering me is that thing between your ears.",
    "We were happily married for one month. Unfortunately, we've been married for 10 years.",
    "A glowstick has a brighter future than you. Lasts longer, too.",
    "If you ever need to find higher ground, you can always try climbing up your own ego.",
    "You are the human version of cramps.",
    "Have you ever tried not being an idiot?",
    "You're like a cloud. When you disappear, it suddenly becomes a beautiful day.",
    "Maybe you should try eating make-up to improve that ugly personality.",
    "If laughter really is the best medicine, your face might just cure the world's deadliest diseases.",
    "You look like something that came out of a slow cooker.",
    "I was thinking about you today. It reminded me to take out the trash.",
    "You have so many gaps in your teeth it looks like your tongue is in jail.",
    "I was going to make a joke about your life, but I see life beat me to the punch.",
    "Oops, my bad. I could've sworn I was dealing with an adult.",
    "It would be a great day if you accidentally used a glue stick instead of a Chapstick.",
    "It's the parent's job to raise their children right. So looking at you, it's obvious that they quit after just one day.",
    "I believe you can achieve anything. Look around; there are plenty of dumb people out there who you could aspire to be.",
    "I bet I could remove 90 percent of your good looks with a moist towelette.",
    "You're like the human version of athlete's foot—annoying and hard to get rid of.",
    "It must be fun to wake up each morning knowing that you are that much closer to achieving your dreams of complete and utter mediocrity.",
    "You're so fake, Barbie might actually be jealous.",
    "You were so happy about testing negative for COVID… we didn't have the heart to tell you it was actually an IQ test.",
    "Tell me something… if I didn't answer you the first time, what makes you think the next 25 attempts will work?",
    "I am jealous of people who have never met you.",
    "Oh, you're talking to me? I thought you only did that behind my back.",
    "Most mistakes can be corrected. You are the exception to the rule.",
    "It is hilarious how you are trying to fit your entire vocabulary into one sentence.",
    "I suggest you do a little soul-searching. You might actually find one.",
    "I know I make a lot of stupid choices, but hanging out with you was the worst one of all.",
    "We were going to roast you, but apparently, burning trash is an environmental hazard.",
    "Hurting you is the last thing I want to do… but it's still on the list.",
    "Everybody knows that you're stupid… thought you could fall in love because you saw a fake Cupid.",
    "I'm not trying to make fun of you, but you can't even count higher than number two.",
    "Roses are red, violets are blue, so many people are pretty, but what happened to you?",
    "It's not my fault, it's everyone's opinion, I'm pretty cool, and you're just a minion.",
    "Poof be gone, your breath is too strong, I don't want to be mean, but you need Listerine.",
    "Don't feel bad, don't feel blue, Frankenstein was ugly too.",
    "If I were a dog and you were a flower, I'd lift my leg up and give you a shower.",
    "Roses are red, monsters are green, look in the mirror, you'll see what I mean.",
    "I'm the type of person to laugh at mistakes, so sorry if I laugh at your face."
}
